# Generated by Django 4.2.3 on 2023-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPdaily",
            fields=[
                (
                    "tscode",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="股票代码",
                    ),
                ),
                (
                    "trade_date",
                    models.CharField(max_length=256, null=True, verbose_name="交易日期"),
                ),
                (
                    "open",
                    models.CharField(max_length=256, null=True, verbose_name="开盘价"),
                ),
                (
                    "high",
                    models.CharField(max_length=256, null=True, verbose_name="最高价"),
                ),
                (
                    "low",
                    models.CharField(max_length=256, null=True, verbose_name="最低价"),
                ),
                (
                    "close",
                    models.CharField(max_length=256, null=True, verbose_name="收盘价"),
                ),
                (
                    "pre_close",
                    models.CharField(max_length=256, null=True, verbose_name="昨日收盘价"),
                ),
                (
                    "change",
                    models.CharField(max_length=256, null=True, verbose_name="涨跌额"),
                ),
                (
                    "pct_chg",
                    models.CharField(max_length=256, null=True, verbose_name="涨跌额"),
                ),
                (
                    "vol",
                    models.CharField(max_length=256, null=True, verbose_name="成交量（手）"),
                ),
                (
                    "amount",
                    models.CharField(max_length=256, null=True, verbose_name="成交额（千元）"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPList",
            fields=[
                (
                    "tscode",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="股票TS",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="股票名称")),
                ("symbol", models.CharField(max_length=16, verbose_name="股票代码")),
                (
                    "industry",
                    models.CharField(max_length=256, null=True, verbose_name="所属行业"),
                ),
                (
                    "list_date",
                    models.CharField(max_length=256, null=True, verbose_name="上市日期"),
                ),
                (
                    "remark",
                    models.CharField(max_length=256, null=True, verbose_name="备注"),
                ),
            ],
        ),
    ]
