# Generated by Django 4.2.1 on 2023-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiao',
            fields=[
                ('name', models.CharField(max_length=16, verbose_name='股票名称')),
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('concept', models.CharField(max_length=256, verbose_name='所属概念')),
                ('business', models.CharField(max_length=256, verbose_name='主营业务')),
                ('Remark', models.CharField(max_length=256, verbose_name='备注')),
            ],
        ),
    ]
