# Generated by Django 4.2.3 on 2023-09-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETFList",
            fields=[
                (
                    "tscode",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="基金代码",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="简称")),
                ("management", models.CharField(max_length=16, verbose_name="管理人")),
                (
                    "fund_type",
                    models.CharField(max_length=256, null=True, verbose_name="投资类型"),
                ),
                (
                    "found_date",
                    models.CharField(max_length=256, null=True, verbose_name="成立日期"),
                ),
                (
                    "issue_date",
                    models.CharField(max_length=256, null=True, verbose_name="发行日期"),
                ),
                (
                    "issue_amount",
                    models.CharField(max_length=256, null=True, verbose_name="发行份额(亿)"),
                ),
                (
                    "invest_type",
                    models.CharField(max_length=256, null=True, verbose_name="投资风格"),
                ),
                (
                    "type",
                    models.CharField(max_length=256, null=True, verbose_name="基金类型"),
                ),
            ],
        ),
    ]
