# Generated by Django 4.2.1 on 2023-06-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_gupiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gupiao',
            old_name='Remark',
            new_name='remark',
        ),
    ]
