# Generated by Django 4.2.1 on 2023-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_remark_gupiao_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gupiao',
            name='business',
            field=models.CharField(max_length=256, null=True, verbose_name='主营业务'),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='concept',
            field=models.CharField(max_length=256, null=True, verbose_name='所属概念'),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='remark',
            field=models.CharField(max_length=256, null=True, verbose_name='备注'),
        ),
    ]
